name: peraktheguide
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.0+5

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  win32: ^5.14.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  http: ^1.4.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  intl: ^0.20.2
  html: ^0.15.6 # Use the version compatible with flutter_html
  flutter_html: ^3.0.0-beta.2
  flutter_inappwebview: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_pdfview: ^1.4.1+1
  flutter_cached_pdfview: ^0.4.3
  flutter_downloader: ^1.12.0
  path_provider: ^2.1.5
  google_mobile_ads: ^6.0.0
  url_launcher: ^6.3.1
  permission_handler: ^12.0.1
  vibration: ^3.1.3
  font_awesome_flutter: ^10.8.0
  package_info_plus: ^8.3.0
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/perak_icon.png"
  min_sdk_android: 23 # android min sdk min:16, default 21


flutter:


  uses-material-design: true

  assets:
    - assets/img/essentials/intro.jpg
    - assets/icon/perak_icon.png
    - assets/img/essentials/getting_around.jpg
    - assets/img/essentials/travel-tips.jpg
    - assets/img/essentials/getting_to_know.jpg
    - assets/img/recommendation/accomodation.jpg
    - assets/img/recommendation/place_to_eat.jpg
    - assets/img/recommendation/place_of_worship.jpg
    - assets/img/essentials/food.jpg
    - assets/img/essentials/getaround/3.-ktm-komuter.png
    - assets/img/essentials/getaround/10.-taxi.png
    - assets/img/essentials/getaround/e-hailing.png
    - assets/img/essentials/iconsofperak/pulau pangkor.jpg
    - assets/img/essentials/iconsofperak/royal belum.jpg
    - assets/img/essentials/iconsofperak/ipoh.jpg
    - assets/img/essentials/iconsofperak/kuala kangsar.jpg
    - assets/img/essentials/iconsofperak/tempurung cave.jpg
    - assets/img/essentials/iconsofperak/Lenggong Valley.jpg
    - assets/img/essentials/iconsofperak/taiping zoo.jpg
    - assets/img/essentials/iconsofperak/orang utan island.jpg
    - assets/img/essentials/iconsofperak/matang mangrove forest.jpg
    - assets/img/essentials/iconsofperak/Sungai Klah Hot Springs.jpg
    - assets/img/essentials/iconsofperak/7lata.jpg
    - assets/img/essentials/food/chicken rice.jpg
    - assets/img/essentials/food/dim sum.jpg
    - assets/img/essentials/food/puff.jpg
    - assets/img/essentials/food/chee cheong fun.jpg
    - assets/img/essentials/food/nasi kandar.jpg
    - assets/img/explore/greateripoh/ipoh/lost world of tambun.jpg
    - assets/img/explore/greateripoh/ipoh/Kek Long Tong Cave.jpg
    - assets/img/explore/greateripoh/ipoh/Concubine Lane.jpg
    - assets/img/explore/greateripoh/ipoh/Kellie_s_Castle_Sideview.jpg
    - assets/img/explore/greateripoh/ipoh/TT5_Tin_Dredge_-_panoramio_(4).jpg
    - assets/img/explore/greateripoh/ipoh/kinta tin mine.jpg
    - assets/img/explore/greateripoh/ipoh/japanese chimney.jpg
    - assets/img/explore/greateripoh/ipoh2.jpg
    - assets/img/explore/greateripoh/ipoh/lost world of tambun.jpg
    - assets/img/explore/peraktengah/peraktengah/Pasir_Salak.jpg
    - assets/img/explore/peraktengah/peraktengah/River Terrapin Conservation Centre.jpg
    - assets/img/explore/peraktengah/pangkor_island.jpg
    - assets/img/explore/peraktengah/peraktengah/teluk senangin.jpg
    - assets/img/explore/peraktengah/peraktengah/Segari Turtle Sanctuary.jpg
    - assets/img/explore/peraktengah/peraktengah/Teluk_Batik.jpg
    - assets/img/explore/peraktengah/peraktengah/jetty.jpg
    - assets/img/explore/peraktengah/perak_tengah2.jpg
    - assets/img/explore/taiping/taiping/Maxwell Hill.jpg
    - assets/img/explore/taiping/taiping/Perak Museum.jpg
    - assets/img/explore/taiping/taiping/Taiping Zoo.jpg
    - assets/img/explore/taiping/kualasepetang/Charcoal Factory Kuala Sepetang.jpg
    - assets/img/explore/taiping/kualasepetang/Matang Mangrove Forest Reserve.jpg
    - assets/img/explore/taiping/kualasepetang/Fireflies Kuala Sepetang.jpg
    - assets/img/explore/taiping/selama/Lata Tebing Tinggi.jpg
    - assets/img/explore/taiping/selama/Sungai Atas Sungai.jpg
    - assets/img/explore/taiping/kerian/Orang Utan Island (Bukit Merah).jpg
    - assets/img/explore/taiping/kerian/Kuala Gula Bird Sanctuary.jpg
    - assets/img/explore/taiping_2.jpg
    - assets/img/explore/kualakangsar/kualakangsar/Labu Sayong.jpg
    - assets/img/explore/kualakangsar/kualakangsar/Laksa Sarang Kuala Kangsar.jpg
    - assets/img/explore/kualakangsar/kualakangsar/Masjid Ihsaniah Iskandariah.jpg
    - assets/img/explore/kualakangsar/kualakangsar/Lenggong Archaeological Gallery.JPG
    - assets/img/explore/kualakangsar/kualakangsar/Restoran Tasik Raban.jpg
    - assets/img/explore/kualakangsar/kualakangsar/Royal Belum State Park.jpg
    - assets/img/explore/kualakangsar/kualakangsar/Rafflesia Park.jpg
    - assets/img/explore/kualakangsar/kualakangsar/tasekTakong.png
    - assets/img/explore/kualakangsar/kualakangsar/GuaGendang.jpg
    - assets/img/explore/kualakangsar/kualakangsar/RahmanHydraulicTinMine.jpg
    - assets/img/explore/kualakangsar/kuala_kangsar.jpg
    - assets/img/explore/telukintan/telukintan/Leaning Tower of Teluk Intan.jpg
    - assets/img/explore/telukintan/telukintan/Pulau Bangau.jpg
    - assets/img/explore/telukintan/telukintan/moccis.jpg
    - assets/img/explore/telukintan/telukintan/Sunflower Garden, Bagan Datuk.jpg
    - assets/img/explore/telukintan/telukintan/bagan sungai burung.jpg
    - assets/img/explore/telukintan/telukintan/Sky Mirror Bagan Datuk.jpg
    - assets/img/explore/telukintan/telukintan/Pulau Sembilan.jpg
    - assets/img/explore/teluk_intan2.jpg
    - assets/img/explore/tanjungmalim/tanjungmalim/Ujana Muallim.jpg
    - assets/img/explore/tanjungmalim/tanjungmalim/National Education Museum.jpg
    - assets/img/explore/tanjungmalim/tanjungmalim/Sarang Art Hub.jpg
    - assets/img/explore/tanjungmalim/tanjungmalim/Sungai Klah Hot Springs.jpg
    - assets/img/explore/tanjungmalim/tanjungmalim/nasi bamboo.jpg
    - assets/img/explore/tanjungmalim/tanjungmalim/Lata Kinjang.jpg
    - assets/img/explore/tanjungmalim/tanjungmalim/Lata Iskandar.jpg
    - assets/img/explore/tanjung_malim.jpg
    - assets/img/recommendation/accommodation/Kampung Air (Water Chalet).jpg
    - assets/img/recommendation/accommodation/The Haven Resort Hotel.jpg
    - assets/img/recommendation/accommodation/The Banjaran Hotspring Retreat.jpg
    - assets/img/recommendation/accommodation/Homestay Bukit Merah Laketown.jpg
    - assets/img/recommendation/accommodation/Dâ€™Rumah Bonda River View.jpg
    - assets/img/recommendation/accommodation/Homestay Gerik Banding.jpg
    - assets/img/recommendation/pte/malay/NasiTalam.jpeg
    - assets/img/recommendation/pte/malay/CastellaCafe.jpeg
    - assets/img/recommendation/pte/chinese/AyamGaram.jpeg
    - assets/img/recommendation/pte/chinese/AyamTaugeh.jpeg
    - assets/img/recommendation/pte/chinese/TongSuiKai.jpeg
    - assets/img/recommendation/pte/indian/YongSuan.jpeg
    - assets/img/recommendation/pte/indian/Samy.jpeg
    - assets/img/recommendation/pte/indian/SriAnandaBahwan.jpeg
    - assets/img/recommendation/pte/cafe/LittleIpoh.jpeg
    - assets/img/recommendation/pte/cafe/AsowEatery.jpeg
    - assets/img/recommendation/pte/cafe/KondaKondi.jpeg
    - assets/img/recommendation/pts/mosque/Ubudiah.jpg
    - assets/img/recommendation/pts/mosque/Panglima.jpeg
    - assets/img/recommendation/pts/mosque/Muhammadiah_Mosque.jpg
    - assets/img/recommendation/pts/buddhist/Sam_Poh_Tong.jpeg
    - assets/img/recommendation/pts/buddhist/Kek_Lok_Tong.jpeg
    - assets/img/recommendation/pts/buddhist/Perak_Cave_Temple.jpg
    - assets/img/recommendation/pts/hindu/SriMahaMariammam.jpg
    - assets/img/recommendation/pts/hindu/ArulmeguMaha.jpg
    - assets/img/recommendation/pts/hindu/KallumalaiArulmigu.jpg
    - assets/img/recommendation/pts/other/StMichael.jpg
    - assets/img/recommendation/pts/other/ChurchOfOurLady.jpg
    - assets/img/recommendation/pts/other/CatholicChurch.jpg


  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
